#!/usr/bin/env python

import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hosts import Host
del sys.path[-1]

info_fields = ["name", "uid", "ip", "username", "conn_type"]

if __name__ == '__main__':
    host = Host.get_by_uid(sys.argv[1])
    for key in info_fields:
        print "%s:\t%s" % (key, getattr(host, key, ""))
